version: "3.1"

services:
  db:
    container_name: servidor_mysql-php
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_ROOT_PASSWORD: pruebadocker
    volumes:
      - /opt/mysql_bookmedik-php:/var/lib/mysql

  bookmedik:
    container_name: bookmedik-php
    image: juanlu/php-imagen:v1
    restart: always
    ports:
      - 8083:80
    volumes:
      - /opt/bookmedik-php:/var/log/apache2
