version: '3.1'

services:
  
  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: dbjoomla
           MYSQL_USER: user
           MYSQL_PASSWORD: userjoom
  
  joomla:
    container_name: joomla
    image: joomla
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: user
      JOOMLA_DB_PASSWORD: userjoom
      JOOMLA_DB_NAME: dbjoomla
